export const env = {
  DETHREADER_FIREBASE_API_KEY: 'AIzaSyCqFTVDX6h2fMqSsvjIRdAqZfkrMqDEDAU',
  DETHREADER_FIREBASE_AUTH_DOMAIN: 'threader-app-8163c.firebaseapp.com',
  DETHREADER_FIREBASE_DATABASE_URL:
    'https://threader-app-8163c-default-rtdb.firebaseio.com',
  DETHREADER_FIREBASE_PROJECT_ID: 'threader-app-8163c',
  DETHREADER_FIREBASE_STORAGE_BUCKET: 'threader-app-8163c.appspot.com',
  DETHREADER_FIREBASE_MESSAGING_SENDER_ID: '1077400049279',
  DETHREADER_FIREBASE_APP_ID: '1:1077400049279:web:af5dee3ccd6b064e3a914a',
  DETHREADER_FIREBASE_MEASUREMENT_ID: 'G-6QQ4CMXDPF',
  CRYPTOJS_SECRET_KEY: 'supersecretkey'
}